configMapGenerator:
- files:
  - application.yml
  name: 82265684-configmap
resources:
- ../../base
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "82265684"
namePrefix: prod-
images:
- name: cepgstapacr.azurecr.io/82265684
  newTag: "202410091600"
- name: cepgstapacr.azurecr.io/cloud-sample
  newTag: "202410090700"
